sudo: required
language: python
services:
  - docker
env:
  global:
    GKE_cluster_name=projects
    GKE_zone=us-central1-c
    GKE_project_id=personal-project-289714

before_install:
  - echo $GCLOUD_SERVICE_KEY_STG | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud components install kubectl

jobs:
  include:
    - stage: build-website
      script:
        - ./docker
    - stage: deploy-website
      script:
        - gcloud container clusters get-credentials $GKE_cluster_name --zone $GKE_zone --project $GKE_project_id
