apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: gcr.io/personal-project-289714/resume
      context: ./
deploy:
  kubectl:
    manifests:
      - kubernetes/local-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: website
    port: 8000
    localPort: 8000
