apiVersion: v1
kind: Service
metadata:
  name: resumesvc
  namespace: resume
  labels:
    app: website
spec:
  selector:
    app: website
    tier: deploy
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: "34.72.241.38"
